### ISSUE TITLE
Use alternative to rack-jekyll to run accessibility tests

### ISSUE THREAD

**Issue by phrdang** [berkeley-cdss/berkeley-class-site#25]
See commit message here: https://github.com/berkeley-eecs/berkeley-class-site/pull/17/commits/e1efa4ef1b2ddd854094bac70e2c34904df64952

See also #17

**Comment by cycomachead** [comment]
In another non-Jekyll static app I used Rack::File directly. It was a fairly simple change, but rack::file is also throwing future deprecation warnings. 

We do need a hook to ensure the Jekyll site is fully built before starting the test run. We could in CI just call Jekyll build and have a dev warning? I mean it's not as nice but in terms of workability it's not a huge deal. 

I haven't looked at what updating rack-Jekyll would be but that honestly shouldn't be a huge dependency.

**Comment by cycomachead** [comment]
OK, well `Rack::File` became `Rack::Files` so that wasn't too hard of a fix, but I do feel like the path mapping is a little awkward...oh well. 

See #37 which was meant to just be styling but then I realized _none_ of the CI tests were actually loading the right CSS so I went down the path of just refactoring a bunch.
